trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'SampleWebApiAspNetCore/SampleWebApiAspNetCore.csproj'
  dockerImageName: 'samplewebapiaspnetcore-webapi'
  containerRegistryName: 'pruvi123'  # Ім'я ACR без .azurecr.io

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildAndTest
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '$(projectPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build'
      continueOnError: true

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: 'az-docker-conn'
        repository: '$(dockerImageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DeployToWebApp
    steps:
    - task: Docker@2
      displayName: 'Push Docker image to ACR'
      inputs:
        containerRegistry: 'az-docker-conn'
        repository: '$(dockerImageName)'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest

    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: 'food-conn'
        appName: 'pruvit123'
        imageName: '$(containerRegistryName).azurecr.io/$(dockerImageName):$(Build.BuildId)'
